<?php

namespace APM\EntitySystem\Schema;

use APM\EntitySystem\Kernel\DefsFromArray;
use APM\EntitySystem\Kernel\EntityDefiner;


const LanguageDefinitions = [
    [ Entity::LangArabic, 'Arabic', 'Arabic Language'],
    [ Entity::LangHebrew, 'Hebrew', 'Hebrew Language'],
    [ Entity::LangLatin, 'Latin', 'Latin Language'],
    [ Entity::LangJudeoArabic, 'Judeo Arabic', 'Judeo Arabic Language'],
    [ Entity::LangAncientGreek, 'Ancient Greek', 'Ancient Greek Language'],
    [ Entity::LangEnglish, 'English', 'English Language'],
    [ Entity::LangGerman, 'German', 'GermanLanguage'],
    [ Entity::LangFrench, 'French', 'French Language'],
    [ Entity::LangItalian, 'Italian', 'Italian Language'],
    [ Entity::LangSpanish, 'Spanish', 'Spanish Language'],
    [ Entity::LangPortuguese, 'Portuguese', 'Portuguese Language'],
    [ Entity::LangTurkish, 'Turkish', 'Turkish Language'],

    [ Entity::LangAfar, 'Afar', 'Afar Language'],
    [ Entity::LangAbkhazian, 'Abkhazian', 'Abkhazian Language'],
    [ Entity::LangAfrikaans, 'Afrikaans', 'Afrikaans Language'],
    [ Entity::LangAmharic, 'Amharic', 'Amharic Language'],
    [ Entity::LangAssamese, 'Assamese', 'Assamese Language'],
    [ Entity::LangAymara, 'Aymara', 'Aymara Language'],
    [ Entity::LangAzerbaijani, 'Azerbaijani', 'Azerbaijani Language'],
    [ Entity::LangBashkir, 'Bashkir', 'Bashkir Language'],
    [ Entity::LangBelarusian, 'Belarusian', 'Belarusian Language'],
    [ Entity::LangBulgarian, 'Bulgarian', 'Bulgarian Language'],
    [ Entity::LangBihari, 'Bihari', 'Bihari Language'],
    [ Entity::LangBislama, 'Bislama', 'Bislama Language'],
    [ Entity::LangBengaliBangla, 'Bengali/Bangla', 'Bengali/Bangla Language'],
    [ Entity::LangTibetan, 'Tibetan', 'Tibetan Language'],
    [ Entity::LangBreton, 'Breton', 'Breton Language'],
    [ Entity::LangCatalan, 'Catalan', 'Catalan Language'],
    [ Entity::LangCorsican, 'Corsican', 'Corsican Language'],
    [ Entity::LangCzech, 'Czech', 'Czech Language'],
    [ Entity::LangWelsh, 'Welsh', 'Welsh Language'],
    [ Entity::LangDanish, 'Danish', 'Danish Language'],
    [ Entity::LangBhutani, 'Bhutani', 'Bhutani Language'],
    [ Entity::LangGreek, 'Greek', 'Greek Language'],
    [ Entity::LangEsperanto, 'Esperanto', 'Esperanto Language'],
    [ Entity::LangEstonian, 'Estonian', 'Estonian Language'],
    [ Entity::LangBasque, 'Basque', 'Basque Language'],
    [ Entity::LangPersian, 'Persian', 'Persian Language'],
    [ Entity::LangFinnish, 'Finnish', 'Finnish Language'],
    [ Entity::LangFiji, 'Fiji', 'Fiji Language'],
    [ Entity::LangFaeroese, 'Faeroese', 'Faeroese Language'],
    [ Entity::LangFrisian, 'Frisian', 'Frisian Language'],
    [ Entity::LangIrish, 'Irish', 'Irish Language'],
    [ Entity::LangScotsGaelic, 'Scots/Gaelic', 'Scots/Gaelic Language'],
    [ Entity::LangGalician, 'Galician', 'Galician Language'],
    [ Entity::LangGuarani, 'Guarani', 'Guarani Language'],
    [ Entity::LangGujarati, 'Gujarati', 'Gujarati Language'],
    [ Entity::LangHausa, 'Hausa', 'Hausa Language'],
    [ Entity::LangHindi, 'Hindi', 'Hindi Language'],
    [ Entity::LangCroatian, 'Croatian', 'Croatian Language'],
    [ Entity::LangHungarian, 'Hungarian', 'Hungarian Language'],
    [ Entity::LangArmenian, 'Armenian', 'Armenian Language'],
    [ Entity::LangInterlingua, 'Interlingua', 'Interlingua Language'],
    [ Entity::LangInterlingue, 'Interlingue', 'Interlingue Language'],
    [ Entity::LangInupiak, 'Inupiak', 'Inupiak Language'],
    [ Entity::LangIndonesian, 'Indonesian', 'Indonesian Language'],
    [ Entity::LangIcelandic, 'Icelandic', 'Icelandic Language'],
    [ Entity::LangJapanese, 'Japanese', 'Japanese Language'],
    [ Entity::LangYiddish, 'Yiddish', 'Yiddish Language'],
    [ Entity::LangJavanese, 'Javanese', 'Javanese Language'],
    [ Entity::LangGeorgian, 'Georgian', 'Georgian Language'],
    [ Entity::LangKazakh, 'Kazakh', 'Kazakh Language'],
    [ Entity::LangGreenlandic, 'Greenlandic', 'Greenlandic Language'],
    [ Entity::LangCambodian, 'Cambodian', 'Cambodian Language'],
    [ Entity::LangKannada, 'Kannada', 'Kannada Language'],
    [ Entity::LangKorean, 'Korean', 'Korean Language'],
    [ Entity::LangKashmiri, 'Kashmiri', 'Kashmiri Language'],
    [ Entity::LangKurdish, 'Kurdish', 'Kurdish Language'],
    [ Entity::LangKirghiz, 'Kirghiz', 'Kirghiz Language'],
    [ Entity::LangLingala, 'Lingala', 'Lingala Language'],
    [ Entity::LangLaothian, 'Laothian', 'Laothian Language'],
    [ Entity::LangLithuanian, 'Lithuanian', 'Lithuanian Language'],
    [ Entity::LangLatvianLettish, 'Latvian/Lettish', 'Latvian/Lettish Language'],
    [ Entity::LangMalagasy, 'Malagasy', 'Malagasy Language'],
    [ Entity::LangMaori, 'Maori', 'Maori Language'],
    [ Entity::LangMacedonian, 'Macedonian', 'Macedonian Language'],
    [ Entity::LangMalayalam, 'Malayalam', 'Malayalam Language'],
    [ Entity::LangMongolian, 'Mongolian', 'Mongolian Language'],
    [ Entity::LangMoldavian, 'Moldavian', 'Moldavian Language'],
    [ Entity::LangMarathi, 'Marathi', 'Marathi Language'],
    [ Entity::LangMalay, 'Malay', 'Malay Language'],
    [ Entity::LangMaltese, 'Maltese', 'Maltese Language'],
    [ Entity::LangBurmese, 'Burmese', 'Burmese Language'],
    [ Entity::LangNauru, 'Nauru', 'Nauru Language'],
    [ Entity::LangNepali, 'Nepali', 'Nepali Language'],
    [ Entity::LangDutch, 'Dutch', 'Dutch Language'],
    [ Entity::LangNorwegian, 'Norwegian', 'Norwegian Language'],
    [ Entity::LangOccitan, 'Occitan', 'Occitan Language'],
    [ Entity::LangAfanOromoorOriya, '(Afan)/Oromoor/Oriya', '(Afan)/Oromoor/Oriya Language'],
    [ Entity::LangPunjabi, 'Punjabi', 'Punjabi Language'],
    [ Entity::LangPolish, 'Polish', 'Polish Language'],
    [ Entity::LangPashtoPushto, 'Pashto/Pushto', 'Pashto/Pushto Language'],
    [ Entity::LangQuechua, 'Quechua', 'Quechua Language'],
    [ Entity::LangRhaetoRomance, 'Rhaeto-Romance', 'Rhaeto-Romance Language'],
    [ Entity::LangKirundi, 'Kirundi', 'Kirundi Language'],
    [ Entity::LangRomanian, 'Romanian', 'Romanian Language'],
    [ Entity::LangRussian, 'Russian', 'Russian Language'],
    [ Entity::LangKinyarwanda, 'Kinyarwanda', 'Kinyarwanda Language'],
    [ Entity::LangSanskrit, 'Sanskrit', 'Sanskrit Language'],
    [ Entity::LangSindhi, 'Sindhi', 'Sindhi Language'],
    [ Entity::LangSangro, 'Sangro', 'Sangro Language'],
    [ Entity::LangSerboCroatian, 'Serbo-Croatian', 'Serbo-Croatian Language'],
    [ Entity::LangSinghalese, 'Singhalese', 'Singhalese Language'],
    [ Entity::LangSlovak, 'Slovak', 'Slovak Language'],
    [ Entity::LangSlovenian, 'Slovenian', 'Slovenian Language'],
    [ Entity::LangSamoan, 'Samoan', 'Samoan Language'],
    [ Entity::LangShona, 'Shona', 'Shona Language'],
    [ Entity::LangSomali, 'Somali', 'Somali Language'],
    [ Entity::LangAlbanian, 'Albanian', 'Albanian Language'],
    [ Entity::LangSerbian, 'Serbian', 'Serbian Language'],
    [ Entity::LangSiswati, 'Siswati', 'Siswati Language'],
    [ Entity::LangSesotho, 'Sesotho', 'Sesotho Language'],
    [ Entity::LangSundanese, 'Sundanese', 'Sundanese Language'],
    [ Entity::LangSwedish, 'Swedish', 'Swedish Language'],
    [ Entity::LangSwahili, 'Swahili', 'Swahili Language'],
    [ Entity::LangTamil, 'Tamil', 'Tamil Language'],
    [ Entity::LangTelugu, 'Telugu', 'Telugu Language'],
    [ Entity::LangTajik, 'Tajik', 'Tajik Language'],
    [ Entity::LangThai, 'Thai', 'Thai Language'],
    [ Entity::LangTigrinya, 'Tigrinya', 'Tigrinya Language'],
    [ Entity::LangTurkmen, 'Turkmen', 'Turkmen Language'],
    [ Entity::LangTagalog, 'Tagalog', 'Tagalog Language'],
    [ Entity::LangSetswana, 'Setswana', 'Setswana Language'],
    [ Entity::LangTonga, 'Tonga', 'Tonga Language'],
    [ Entity::LangTsonga, 'Tsonga', 'Tsonga Language'],
    [ Entity::LangTatar, 'Tatar', 'Tatar Language'],
    [ Entity::LangTwi, 'Twi', 'Twi Language'],
    [ Entity::LangUkrainian, 'Ukrainian', 'Ukrainian Language'],
    [ Entity::LangUrdu, 'Urdu', 'Urdu Language'],
    [ Entity::LangUzbek, 'Uzbek', 'Uzbek Language'],
    [ Entity::LangVietnamese, 'Vietnamese', 'Vietnamese Language'],
    [ Entity::LangVolapuk, 'Volapuk', 'Volapuk Language'],
    [ Entity::LangWolof, 'Wolof', 'Wolof Language'],
    [ Entity::LangXhosa, 'Xhosa', 'Xhosa Language'],
    [ Entity::LangYoruba, 'Yoruba', 'Yoruba Language'],
    [ Entity::LangChinese, 'Chinese', 'Chinese Language'],
    [ Entity::LangZulu, 'Zulu', 'Zulu Language'],
];

const IsoCodes = [
    [ Entity::LangArabic,  'ar'],
    [ Entity::LangHebrew,  'he'],
    [ Entity::LangLatin,   'la'],
    [ Entity::LangJudeoArabic,  'jrb'],
    [ Entity::LangAncientGreek, 'grc'],
    [ Entity::LangEnglish, 'en'],
    [ Entity::LangGerman,  'de'],
    [ Entity::LangFrench,  'fr'],
    [ Entity::LangItalian, 'it'],
    [ Entity::LangSpanish, 'es'],
    [ Entity::LangPortuguese,  'pt'],
    [ Entity::LangTurkish, 'tr'],

    [ Entity::LangAfar, 'aa'],
    [ Entity::LangAbkhazian, 'ab'],
    [ Entity::LangAfrikaans, 'af'],
    [ Entity::LangAmharic, 'am'],
    [ Entity::LangAssamese, 'as'],
    [ Entity::LangAymara, 'ay'],
    [ Entity::LangAzerbaijani, 'az'],
    [ Entity::LangBashkir, 'ba'],
    [ Entity::LangBelarusian, 'be'],
    [ Entity::LangBulgarian, 'bg'],
    [ Entity::LangBihari, 'bh'],
    [ Entity::LangBislama, 'bi'],
    [ Entity::LangBengaliBangla, 'bn'],
    [ Entity::LangTibetan, 'bo'],
    [ Entity::LangBreton, 'br'],
    [ Entity::LangCatalan, 'ca'],
    [ Entity::LangCorsican, 'co'],
    [ Entity::LangCzech, 'cs'],
    [ Entity::LangWelsh, 'cy'],
    [ Entity::LangDanish, 'da'],
    [ Entity::LangBhutani, 'dz'],
    [ Entity::LangGreek, 'el'],
    [ Entity::LangEsperanto, 'eo'],
    [ Entity::LangEstonian, 'et'],
    [ Entity::LangBasque, 'eu'],
    [ Entity::LangPersian, 'fa'],
    [ Entity::LangFinnish, 'fi'],
    [ Entity::LangFiji, 'fj'],
    [ Entity::LangFaeroese, 'fo'],
    [ Entity::LangFrisian, 'fy'],
    [ Entity::LangIrish, 'ga'],
    [ Entity::LangScotsGaelic, 'gd'],
    [ Entity::LangGalician, 'gl'],
    [ Entity::LangGuarani, 'gn'],
    [ Entity::LangGujarati, 'gu'],
    [ Entity::LangHausa, 'ha'],
    [ Entity::LangHindi, 'hi'],
    [ Entity::LangCroatian, 'hr'],
    [ Entity::LangHungarian, 'hu'],
    [ Entity::LangArmenian, 'hy'],
    [ Entity::LangInterlingua, 'ia'],
    [ Entity::LangInterlingue, 'ie'],
    [ Entity::LangInupiak, 'ik'],
    [ Entity::LangIndonesian, 'in'],
    [ Entity::LangIcelandic, 'is'],
    [ Entity::LangJapanese, 'ja'],
    [ Entity::LangYiddish, 'ji'],
    [ Entity::LangJavanese, 'jw'],
    [ Entity::LangGeorgian, 'ka'],
    [ Entity::LangKazakh, 'kk'],
    [ Entity::LangGreenlandic, 'kl'],
    [ Entity::LangCambodian, 'km'],
    [ Entity::LangKannada, 'kn'],
    [ Entity::LangKorean, 'ko'],
    [ Entity::LangKashmiri, 'ks'],
    [ Entity::LangKurdish, 'ku'],
    [ Entity::LangKirghiz, 'ky'],
    [ Entity::LangLingala, 'ln'],
    [ Entity::LangLaothian, 'lo'],
    [ Entity::LangLithuanian, 'lt'],
    [ Entity::LangLatvianLettish, 'lv'],
    [ Entity::LangMalagasy, 'mg'],
    [ Entity::LangMaori, 'mi'],
    [ Entity::LangMacedonian, 'mk'],
    [ Entity::LangMalayalam, 'ml'],
    [ Entity::LangMongolian, 'mn'],
    [ Entity::LangMoldavian, 'mo'],
    [ Entity::LangMarathi, 'mr'],
    [ Entity::LangMalay, 'ms'],
    [ Entity::LangMaltese, 'mt'],
    [ Entity::LangBurmese, 'my'],
    [ Entity::LangNauru, 'na'],
    [ Entity::LangNepali, 'ne'],
    [ Entity::LangDutch, 'nl'],
    [ Entity::LangNorwegian, 'no'],
    [ Entity::LangOccitan, 'oc'],
    [ Entity::LangAfanOromoorOriya, 'om'],
    [ Entity::LangPunjabi, 'pa'],
    [ Entity::LangPolish, 'pl'],
    [ Entity::LangPashtoPushto, 'ps'],
    [ Entity::LangQuechua, 'qu'],
    [ Entity::LangRhaetoRomance, 'rm'],
    [ Entity::LangKirundi, 'rn'],
    [ Entity::LangRomanian, 'ro'],
    [ Entity::LangRussian, 'ru'],
    [ Entity::LangKinyarwanda, 'rw'],
    [ Entity::LangSanskrit, 'sa'],
    [ Entity::LangSindhi, 'sd'],
    [ Entity::LangSangro, 'sg'],
    [ Entity::LangSerboCroatian, 'sh'],
    [ Entity::LangSinghalese, 'si'],
    [ Entity::LangSlovak, 'sk'],
    [ Entity::LangSlovenian, 'sl'],
    [ Entity::LangSamoan, 'sm'],
    [ Entity::LangShona, 'sn'],
    [ Entity::LangSomali, 'so'],
    [ Entity::LangAlbanian, 'sq'],
    [ Entity::LangSerbian, 'sr'],
    [ Entity::LangSiswati, 'ss'],
    [ Entity::LangSesotho, 'st'],
    [ Entity::LangSundanese, 'su'],
    [ Entity::LangSwedish, 'sv'],
    [ Entity::LangSwahili, 'sw'],
    [ Entity::LangTamil, 'ta'],
    [ Entity::LangTelugu, 'te'],
    [ Entity::LangTajik, 'tg'],
    [ Entity::LangThai, 'th'],
    [ Entity::LangTigrinya, 'ti'],
    [ Entity::LangTurkmen, 'tk'],
    [ Entity::LangTagalog, 'tl'],
    [ Entity::LangSetswana, 'tn'],
    [ Entity::LangTonga, 'to'],
    [ Entity::LangTsonga, 'ts'],
    [ Entity::LangTatar, 'tt'],
    [ Entity::LangTwi, 'tw'],
    [ Entity::LangUkrainian, 'uk'],
    [ Entity::LangUrdu, 'ur'],
    [ Entity::LangUzbek, 'uz'],
    [ Entity::LangVietnamese, 'vi'],
    [ Entity::LangVolapuk, 'vo'],
    [ Entity::LangWolof, 'wo'],
    [ Entity::LangXhosa, 'xh'],
    [ Entity::LangYoruba, 'yo'],
    [ Entity::LangChinese, 'zh'],
    [ Entity::LangZulu, 'zu'],
];

class Languages implements EntityDefiner
{
    /**
     * @inheritDoc
     */
    public function getEntityDefinitions(): array
    {
      return DefsFromArray::getEntityDefinitionsFromArray(LanguageDefinitions, Entity::tLanguage);
    }

    /**
     * @inheritDoc
     */
    public function getStatements(): array
    {
        $statements = [];
        foreach (IsoCodes as $codeDefinition) {
            [ $id, $code ] = $codeDefinition;
            $statements[] = [ $id, Entity::pLangIso639Code, $code];
        }
        return $statements;
    }
}


