#!/usr/bin/php -q
<?php

/*
 *  Copyright (C) 2020 Universität zu Köln
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 */


/**
 * Generates a bash script to convert a PDF into jpgs
 */

if ($argc != 4) {
    print "convertpdf <filename> <numpages> <outdir>\n";
    return false;
}

$fileName = $argv[1];
$numPages = intval($argv[2]);
$outDir = $argv[3];

if ($numPages < 1) {
    print "Num pages must be greater than 1\n";
    return false;
}



for ($i = 0; $i < $numPages; $i++){
    $pngFileName = sprintf("/tmp/%s-%04d.png", $fileName, $i+1);
    $outFileName = sprintf("%s/%s-%04d.jpg", $outDir, $fileName, $i+1);
    printf("convert -density 300 %s.pdf[%d] -alpha remove -background white -flatten %s\n", $fileName, $i, $pngFileName);
    printf("convert %s %s\n", $pngFileName, $outFileName);
    printf("rm $pngFileName\n");
}

