#!/usr/bin/php -q
<?php

/* 
 *  Copyright (C) 2016 Universität zu Köln
 *  
 *  This program is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU General Public License
 *  as published by the Free Software Foundation; either version 2
 *  of the License, or (at your option) any later version.
 *   
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *  
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 *  
 */

if ($argc != 3) {
    print "ls -1 <somefiles> | renamefiles <prefix> <starting id>\n";
    return false;
}

$prefix = $argv[1];
$i = (int) $argv[2];

if ($i <= 0) {
    print("ERROR: Starting Id must be >= 0");
    return false;
}

while($f = fgets(STDIN)){
    $f = rtrim($f);
    $fields = explode('.', $f);
    $extension = array_pop($fields);
    if ($extension === 'jpg' || $extension === 'JPG') {
        printf("mv %s %s-%04d.jpg\n", $f, $prefix, $i++);
    }
}

return true;