#
# Docker compose file for an Opensearch node for development
# Data is persisted in the opensearch-apm-data volume
#

services:
  apm-opensearch:
    image: opensearchproject/opensearch:2.18.0
    container_name: apm-opensearch
    environment:
      - cluster.name=apm-opensearch-cluster
      - node.name=apm-opensearch
      - discovery.type=single-node
      - plugins.security.disabled=true # API is completely open, which is fine even for production if the machine is secured
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "OPENSEARCH_INITIAL_ADMIN_PASSWORD=!MySampl3ApmOpenSearchConfig"
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # half a gig of RAM should be plenty since APM indices are fairly small
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - opensearch-apm-data:/usr/share/opensearch/data
    ports:
      - "9200:9200" # may need to change if running other opensearch instances (e.g. for DARE and SIRE)
      - "9600:9600" # required for Performance Analyzer
    networks:
      - opensearch-net
#  opensearch-dashboards:
#    image: opensearchproject/opensearch-dashboards:2.3.0
#    container_name: opensearch-dashboards
#    ports:
#      - "5601:5601"
#    expose:
#      - "5601"
#    environment:
#      OPENSEARCH_HOSTS: '["https://opensearch-apm:9200"]'
#    networks:
#      - opensearch-net

volumes:
  opensearch-apm-data:

networks:
  opensearch-net: