#!/usr/bin/php -q
<?php

/*
 *  Copyright (C) 2019 Universität zu Köln
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 */

namespace APM;

use APM\System\ConfigLoader;

require __DIR__ . '/../vendor/autoload.php';

$config = SystemConfig::get();
if (!is_array($config)) {
    print "ERROR: $config\n";
    exit(1);
}

(new CommandLine\MigrateAutomaticCollationPresets($config, $argc, $argv))->run();
