#!/bin/bash
#
#
#  Copyright (C) 2019-2026 Universität zu Köln
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.

#
# apm-createdist.bash
#
# Creates a distribution tar file for apm 
#
# Author: Rafael Nájera <rafael.najera@uni-koeln.de>
#


USAGE="USAGE: apm-createdist <version> <base dir, e.g. '/apm' or ''> [--mac]"

if (("$#" < 2)) ; then
   echo "$USAGE"
   exit
fi

VERSION=$1
BASE_DIR=$2
MAC=$3

if [[ $BASE_DIR != /* ]]; then
  echo "Error: base dir must start with '/' " >&2
  exit 1
fi

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
APM_SRC_BASE="$SCRIPT_DIR/../apps/apm/src"
TMP=/tmp
DIST_NAME=apm-$VERSION
DIST_DIR="$SCRIPT_DIR/../dist"
CUR_DIR=$(pwd)
TMP_DIR=$TMP/$DIST_NAME
TAR_NAME=$DIST_NAME.tar.gz

NPM_BUILD_FRONTEND="cd \"$APM_SRC_BASE/www\"; npm run build -- --base=$BASE_DIR/dist; cd \"$SCRIPT_DIR\""
NPM_BUILD_TYPESETTING="cd \"$APM_SRC_BASE/typesetting-service\"; npm run build; cd \"$SCRIPT_DIR\""

echo Creating temporary directory
if [ -d "$TMP_DIR" ]
then
  rm -fr "$TMP_DIR" || exit
fi

mkdir "$TMP_DIR" || exit

echo Building frontend JS for production with base dir "$BASE_DIR"
eval "$NPM_BUILD_FRONTEND"

echo Building typesetting service JS for production
eval "$NPM_BUILD_TYPESETTING"

echo Copying files to temporary directory
cp -R $APM_SRC_BASE/typesetting-service "$TMP_DIR"
cp -R $APM_SRC_BASE/db "$TMP_DIR"
cp -R $APM_SRC_BASE/bin "$TMP_DIR"
mkdir "$TMP_DIR"/www || exit

cp -R $APM_SRC_BASE/www/classes "$TMP_DIR"/www
cp -R $APM_SRC_BASE/www/css "$TMP_DIR"/www
cp -R $APM_SRC_BASE/www/images "$TMP_DIR"/www
cp -R $APM_SRC_BASE/www/hyphenation "$TMP_DIR"/www
cp -R $APM_SRC_BASE/www/fonts "$TMP_DIR"/www
cp -R $APM_SRC_BASE/www/templates "$TMP_DIR"/www
cp -R $APM_SRC_BASE/www/utilities "$TMP_DIR"/www
cp -R $APM_SRC_BASE/www/vendor "$TMP_DIR"/www
cp -R $APM_SRC_BASE/www/node_modules "$TMP_DIR"/www
cp -R $APM_SRC_BASE/www/dist "$TMP_DIR"/www

cp $APM_SRC_BASE/www/composer.json "$TMP_DIR"/www
cp $APM_SRC_BASE/www/composer.lock "$TMP_DIR"/www
cp $APM_SRC_BASE/www/package.json "$TMP_DIR"/www
cp $APM_SRC_BASE/www/package-lock.json "$TMP_DIR"/www
cp $APM_SRC_BASE/www/version.yaml "$TMP_DIR"/www
cp $APM_SRC_BASE/www/defaults.yaml "$TMP_DIR"/www
cp $APM_SRC_BASE/www/config.sample.yaml "$TMP_DIR"/www
cp $APM_SRC_BASE/www/index.php "$TMP_DIR"/www

cp -R $APM_SRC_BASE/www/js "$TMP_DIR"/www
rm -fr "$TMP_DIR"/www/js/istanbul
rm -f "$TMP_DIR"/www/js/Makefile
rm -f "$TMP_DIR"/www/js/.eslintrc.json

mkdir "$TMP_DIR"/www/downloads
chmod a+w "$TMP_DIR"/www/downloads

mkdir "$TMP_DIR"/www/downloads/pdf
chmod a+w "$TMP_DIR"/www/downloads/pdf

cd "$TMP" || exit


echo "Creating tar file $DIST_DIR/$TAR_NAME"
if [ "$MAC" = "--mac" ]
then
  COPYFILE_DISABLE=1; export COPYFILE_DISABLE
  COPY_EXTENDED_ATTRIBUTES_DISABLE=1; export COPY_EXTENDED_ATTRIBUTES_DISABLE
fi

tar cfz "$TAR_NAME" "$DIST_NAME"
rm -fr "$DIST_NAME"
mv "$TAR_NAME" "$DIST_DIR"/

cd "$CUR_DIR" || exit
