<?php

namespace APM\EntitySystem\Schema;

use APM\EntitySystem\Kernel\DefsFromArray;
use APM\EntitySystem\Kernel\PredicateDefiner;


const DocumentPredicateDefs = [
    [
        'id' => Entity::pDocumentType,
        'type' => Entity::tRelation,
        'name' => 'Document Type',
        'descr' => "The document's type: mss, print, etc",
        'allowedSubjectTypes' => [ Entity::tDocument],
        'allowedObjectTypes'=> [ Entity::tDocumentType],
        'canBeCancelled' => false,
        'singleProperty' => true,
        'flags' => []
    ],
    [
        'id' => Entity::pDocumentLanguage,
        'type' => Entity::tRelation,
        'name' => 'Document Language',
        'descr' => "The document's main language",
        'allowedSubjectTypes' => [ Entity::tDocument],
        'allowedObjectTypes'=> [ Entity::tLanguage],
        'canBeCancelled' => true,
        'singleProperty' => true,
        'flags' => []
    ],
    [
        'id' => Entity::pImageSource,
        'type' => Entity::tRelation,
        'name' => 'Image Source',
        'descr' => "The document's image source",
        'allowedSubjectTypes' => [ Entity::tDocument],
        'allowedObjectTypes'=> [ Entity::tImageSource],
        'canBeCancelled' => true, // if not present, no images will be displayed for the document
        'singleProperty' => true,
        'flags' => []
    ],
    [
        'id' => Entity::pInDare,
        'type' => Entity::tAttribute,
        'name' => 'Defined in DARE',
        'descr' => "If true, the document is defined in DARE",
        'allowedSubjectTypes' => [ Entity::tDocument],
        'allowedObjectTypes'=> [ Entity::ValueTypeBoolean],
        'canBeCancelled' => true,
        'singleProperty' => true,
        'flags' => []
    ],
    [
        'id' => Entity::pIsPublic,
        'type' => Entity::tAttribute,
        'name' => 'Public Document',
        'descr' => "If true, the document is public (Legacy attribute: not used in APM anymore)",
        'allowedSubjectTypes' => [ Entity::tDocument],
        'allowedObjectTypes'=> [ Entity::ValueTypeBoolean],
        'canBeCancelled' => true,
        'singleProperty' => true,
        'flags' => []
    ],
    [
        'id' => Entity::pImageSourceData,
        'type' => Entity::tAttribute,
        'name' => 'Image Source Data',
        'descr' => "Data needed to identify the document's images on the image source",
        'allowedSubjectTypes' => [ Entity::tDocument],
        'allowedObjectTypes'=> [ Entity::ValueTypeText],
        'canBeCancelled' => true,
        'singleProperty' => true,
        'flags' => [ ]
    ],
    [
        'id' => Entity::pUseDeepZoomForImages,
        'type' => Entity::tAttribute,
        'name' => 'Use Deep Zoom for Images',
        'descr' => "If true, the images will be presented with deep zoom",
        'allowedSubjectTypes' => [ Entity::tDocument],
        'allowedObjectTypes'=> [ Entity::ValueTypeBoolean],
        'canBeCancelled' => true,
        'singleProperty' => true,
        'flags' => []
    ],
    [
        'id' => Entity::pStoredAt,
        'type' => Entity::tRelation,
        'name' => 'Place of Storage',
        'descr' => "Describes, where a document is stored.",
        'allowedSubjectTypes' => [ Entity::tDocument],
        'allowedObjectTypes'=> [ Entity::tInstitution],
        'canBeCancelled' => true,
        'singleProperty' => true,
        'flags' => []
    ],
    [
        'id' => Entity::pDareType,
        'type' => Entity::tAttribute,
        'name' => 'Dare Document Type',
        'descr' => "Describes the type of a document in Dare.",
        'allowedSubjectTypes' => [Entity::tDocument],
        'allowedObjectTypes'=> null,
        'canBeCancelled' => true,
        'singleProperty' => true,
        'flags' => [],
    ],
    [
        'id' => Entity::pDareHasImages,
        'type' => Entity::tAttribute,
        'name' => 'Has Images (Dare)',
        'descr' => "Describes if a document has images in Dare.",
        'allowedSubjectTypes' => [Entity::tDocument],
        'allowedObjectTypes'=> null,
        'canBeCancelled' => true,
        'singleProperty' => true,
        'flags' => [],
    ],
    [
        'id' => Entity::pDareImagesComplete,
        'type' => Entity::tAttribute,
        'name' => 'Images Complete (Dare)',
        'descr' => "Describes if the images of a document in Dare are complete.",
        'allowedSubjectTypes' => [Entity::tDocument],
        'allowedObjectTypes'=> null,
        'canBeCancelled' => true,
        'singleProperty' => true,
        'flags' => [],
    ],
    [
        'id' => Entity::pDareHasPlaceholders,
        'type' => Entity::tAttribute,
        'name' => 'Has Placeholders (Dare)',
        'descr' => "Describes if a document has placeholders.",
        'allowedSubjectTypes' => [Entity::tDocument],
        'allowedObjectTypes'=> null,
        'canBeCancelled' => true,
        'singleProperty' => true,
        'flags' => [],
    ],
    [
        'id' => Entity::pDareIsFragmentary,
        'type' => Entity::tAttribute,
        'name' => 'Is Fragmentary (Dare)',
        'descr' => "Describes if a document is fragmentary.",
        'allowedSubjectTypes' => [Entity::tDocument],
        'allowedObjectTypes'=> null,
        'canBeCancelled' => true,
        'singleProperty' => true,
        'flags' => [],
    ],
    [
        'id' => Entity::pDareIsDareFoliated,
        'type' => Entity::tAttribute,
        'name' => 'Is Dare Foliated (Dare)',
        'descr' => "Describes if the document is dare-foliated.",
        'allowedSubjectTypes' => [Entity::tDocument],
        'allowedObjectTypes'=> null,
        'canBeCancelled' => true,
        'singleProperty' => true,
        'flags' => [],
    ],
    [
        'id' => Entity::pDarePageCount,
        'type' => Entity::tAttribute,
        'name' => 'Page Count (Dare)',
        'descr' => "Describes the number of pages of a document.",
        'allowedSubjectTypes' => [Entity::tDocument],
        'allowedObjectTypes'=> null,
        'canBeCancelled' => true,
        'singleProperty' => true,
        'flags' => [],
    ],
    [
        'id' => Entity::pDareIdno,
        'type' => Entity::tAttribute,
        'name' => 'Document ID (Dare)',
        'descr' => "Describes the id of a document.",
        'allowedSubjectTypes' => [Entity::tDocument],
        'allowedObjectTypes'=> null,
        'canBeCancelled' => true,
        'singleProperty' => true,
        'flags' => [],
    ],
    [
        'id' => Entity::pDareAltRepository,
        'type' => Entity::tAttribute,
        'name' => 'Alternative Repository (Dare)',
        'descr' => "Describes (an) alternative repository/ies of a document.",
        'allowedSubjectTypes' => [Entity::tDocument],
        'allowedObjectTypes'=> null,
        'canBeCancelled' => true,
        'singleProperty' => true,
        'flags' => [],
    ],
    [
        'id' => Entity::pDareContentTitle,
        'type' => Entity::tAttribute,
        'name' => 'Content Title (Dare)',
        'descr' => "Describes the content title of a document.",
        'allowedSubjectTypes' => [Entity::tDocument],
        'allowedObjectTypes'=> null,
        'canBeCancelled' => true,
        'singleProperty' => true,
        'flags' => [],
    ],
    [
        'id' => Entity::pDareContentSummary,
        'type' => Entity::tAttribute,
        'name' => 'Content Summary (Dare)',
        'descr' => "Describes the content of a document.",
        'allowedSubjectTypes' => [Entity::tDocument],
        'allowedObjectTypes'=> null,
        'canBeCancelled' => true,
        'singleProperty' => true,
        'flags' => [],
    ],
    [
        'id' => Entity::pDareIsSegmented,
        'type' => Entity::tAttribute,
        'name' => 'Is Segmented (Dare)',
        'descr' => "Describes if a document is segmented.",
        'allowedSubjectTypes' => [Entity::tDocument],
        'allowedObjectTypes'=> null,
        'canBeCancelled' => true,
        'singleProperty' => true,
        'flags' => [],
    ],
    [
        'id' => Entity::pDareLeavesCount,
        'type' => Entity::tAttribute,
        'name' => 'Leaves Count (Dare)',
        'descr' => "Describes how many leaves a document has.",
        'allowedSubjectTypes' => [Entity::tDocument],
        'allowedObjectTypes'=> null,
        'canBeCancelled' => true,
        'singleProperty' => true,
        'flags' => [],
    ],
    [
        'id' => Entity::pDareMaterialType,
        'type' => Entity::tRelation,
        'name' => 'Material Type (Dare)',
        'descr' => "Describes the material type of a document.",
        'allowedSubjectTypes' => [Entity::tDocument],
        'allowedObjectTypes'=> [Entity::tDareMaterial],
        'canBeCancelled' => true,
        'singleProperty' => true,
        'flags' => [],
    ],
    [
        'id' => Entity::pDareLeavesFormat,
        'type' => Entity::tAttribute,
        'name' => 'Leaves Format (Dare)',
        'descr' => "Describes the format of the leaves of a document.",
        'allowedSubjectTypes' => [Entity::tDocument],
        'allowedObjectTypes'=> null,
        'canBeCancelled' => true,
        'singleProperty' => true,
        'flags' => [],
    ],
    [
        'id' => Entity::pDareLeavesHeight,
        'type' => Entity::tAttribute,
        'name' => 'Leaves Height (Dare)',
        'descr' => "Describes the height of the leaves of a document.",
        'allowedSubjectTypes' => [Entity::tDocument],
        'allowedObjectTypes'=> null,
        'canBeCancelled' => true,
        'singleProperty' => true,
        'flags' => [],
    ],
    [
        'id' => Entity::pDareLeavesWidth,
        'type' => Entity::tAttribute,
        'name' => 'Leaves Width (Dare)',
        'descr' => "Describes the width of the leaves of a document.",
        'allowedSubjectTypes' => [Entity::tDocument],
        'allowedObjectTypes'=> null,
        'canBeCancelled' => true,
        'singleProperty' => true,
        'flags' => [],
    ],
    [
        'id' => Entity::pDareWrittenLines,
        'type' => Entity::tAttribute,
        'name' => 'Written Lines (Dare)',
        'descr' => "Describes the number of written lines of a document.",
        'allowedSubjectTypes' => [Entity::tDocument],
        'allowedObjectTypes'=> null,
        'canBeCancelled' => true,
        'singleProperty' => true,
        'flags' => [],
    ],
    [
        'id' => Entity::pDareWrittenLinesText,
        'type' => Entity::tAttribute,
        'name' => 'Written Lines Text (Dare)',
        'descr' => "Describes the number of written lines of text in a document.",
        'allowedSubjectTypes' => [Entity::tDocument],
        'allowedObjectTypes'=> null,
        'canBeCancelled' => true,
        'singleProperty' => true,
        'flags' => [],
    ],
    [
        'id' => Entity::pDareColumnNo,
        'type' => Entity::tAttribute,
        'name' => 'Column Number (Dare)',
        'descr' => "Describes the number of columns in a document.",
        'allowedSubjectTypes' => [Entity::tDocument],
        'allowedObjectTypes'=> null,
        'canBeCancelled' => true,
        'singleProperty' => true,
        'flags' => [],
    ],
    [
        'id' => Entity::pDareWrittenHeight,
        'type' => Entity::tAttribute,
        'name' => 'Written Height (Dare)',
        'descr' => "Describes the written height of a document.",
        'allowedSubjectTypes' => [Entity::tDocument],
        'allowedObjectTypes'=> null,
        'canBeCancelled' => true,
        'singleProperty' => true,
        'flags' => [],
    ],
    [
        'id' => Entity::pDareWrittenWidth,
        'type' => Entity::tAttribute,
        'name' => 'Written Width (Dare)',
        'descr' => "Describes the written width in a document.",
        'allowedSubjectTypes' => [Entity::tDocument],
        'allowedObjectTypes'=> null,
        'canBeCancelled' => true,
        'singleProperty' => true,
        'flags' => [],
    ],
    [
        'id' => Entity::pDareHandNumber,
        'type' => Entity::tAttribute,
        'name' => 'Hand Number (Dare)',
        'descr' => "Describes the hand number of a document.",
        'allowedSubjectTypes' => [Entity::tDocument],
        'allowedObjectTypes'=> null,
        'canBeCancelled' => true,
        'singleProperty' => true,
        'flags' => [],
    ],
    [
        'id' => Entity::pDareContemporaryBinding,
        'type' => Entity::tAttribute,
        'name' => 'Contemporary Binding (Dare)',
        'descr' => "Describes the contemporary binding of a document.",
        'allowedSubjectTypes' => [Entity::tDocument],
        'allowedObjectTypes'=> null,
        'canBeCancelled' => true,
        'singleProperty' => true,
        'flags' => [],
    ],
    [
        'id' => Entity::pDareBindingWidth,
        'type' => Entity::tAttribute,
        'name' => 'Binding Width (Dare)',
        'descr' => "Describes the binding width of a document.",
        'allowedSubjectTypes' => [Entity::tDocument],
        'allowedObjectTypes'=> null,
        'canBeCancelled' => true,
        'singleProperty' => true,
        'flags' => [],
    ],
    [
        'id' => Entity::pDareBindingHeight,
        'type' => Entity::tAttribute,
        'name' => 'Binding Height (Dare)',
        'descr' => "Describes the binding height of a document.",
        'allowedSubjectTypes' => [Entity::tDocument],
        'allowedObjectTypes'=> null,
        'canBeCancelled' => true,
        'singleProperty' => true,
        'flags' => [],
    ],
    [
        'id' => Entity::pDareBindingDate,
        'type' => Entity::tAttribute,
        'name' => 'Binding Date (Dare)',
        'descr' => "Describes the binding date of a document.",
        'allowedSubjectTypes' => [Entity::tDocument],
        'allowedObjectTypes'=> null,
        'canBeCancelled' => true,
        'singleProperty' => true,
        'flags' => [],
    ],
    [
        'id' => Entity::pDareOriginNotBefore,
        'type' => Entity::tAttribute,
        'name' => 'Origin Not Before (Dare)',
        'descr' => "Describes the earliest possible origin date of a document.",
        'allowedSubjectTypes' => [Entity::tDocument],
        'allowedObjectTypes'=> null,
        'canBeCancelled' => true,
        'singleProperty' => true,
        'flags' => [],
    ],
    [
        'id' => Entity::pDareOriginNotAfter,
        'type' => Entity::tAttribute,
        'name' => 'Origin Not After (Dare)',
        'descr' => "Describes the latest possible origin date of a document.",
        'allowedSubjectTypes' => [Entity::tDocument],
        'allowedObjectTypes'=> null,
        'canBeCancelled' => true,
        'singleProperty' => true,
        'flags' => [],
    ],
    [
        'id' => Entity::pDareOriginDate,
        'type' => Entity::tAttribute,
        'name' => 'Origin Date (Dare)',
        'descr' => "Describes the origin date of a document.",
        'allowedSubjectTypes' => [Entity::tDocument],
        'allowedObjectTypes'=> null,
        'canBeCancelled' => true,
        'singleProperty' => true,
        'flags' => [],
    ],
    [
        'id' => Entity::pDareOriginPlace,
        'type' => Entity::tAttribute,
        'name' => 'Origin Place (Dare)',
        'descr' => "Describes the origin place of a document.",
        'allowedSubjectTypes' => [Entity::tDocument],
        'allowedObjectTypes'=> null,
        'canBeCancelled' => true,
        'singleProperty' => true,
        'flags' => [],
    ],
    [
        'id' => Entity::pDareFoliation,
        'type' => Entity::tAttribute,
        'name' => 'Foliation (Dare)',
        'descr' => "Describes the foliation of a document.",
        'allowedSubjectTypes' => [Entity::tDocument],
        'allowedObjectTypes'=> null,
        'canBeCancelled' => true,
        'singleProperty' => true,
        'flags' => [],
    ],
    [
        'id' => Entity::pDareCollation,
        'type' => Entity::tAttribute,
        'name' => 'Collation (Dare)',
        'descr' => "Describes the collation of a document.",
        'allowedSubjectTypes' => [Entity::tDocument],
        'allowedObjectTypes'=> null,
        'canBeCancelled' => true,
        'singleProperty' => true,
        'flags' => [],
    ],
    [
        'id' => Entity::pDareConditionDescription,
        'type' => Entity::tAttribute,
        'name' => 'Condition Description (Dare)',
        'descr' => "Describes the condition of a document.",
        'allowedSubjectTypes' => [Entity::tDocument],
        'allowedObjectTypes'=> null,
        'canBeCancelled' => true,
        'singleProperty' => true,
        'flags' => [],
    ],
    [
        'id' => Entity::pDareDecoration,
        'type' => Entity::tAttribute,
        'name' => 'Decoration (Dare)',
        'descr' => "Describes the decoration of a document.",
        'allowedSubjectTypes' => [Entity::tDocument],
        'allowedObjectTypes'=> null,
        'canBeCancelled' => true,
        'singleProperty' => true,
        'flags' => [],
    ],
    [
        'id' => Entity::pDareLayout,
        'type' => Entity::tAttribute,
        'name' => 'Layout (Dare)',
        'descr' => "Describes the layout of a document.",
        'allowedSubjectTypes' => [Entity::tDocument],
        'allowedObjectTypes'=> null,
        'canBeCancelled' => true,
        'singleProperty' => true,
        'flags' => [],
    ],
    [
        'id' => Entity::pDareHandDescription,
        'type' => Entity::tAttribute,
        'name' => 'Hand Description (Dare)',
        'descr' => "Describes the handwriting in a document.",
        'allowedSubjectTypes' => [Entity::tDocument],
        'allowedObjectTypes'=> null,
        'canBeCancelled' => true,
        'singleProperty' => true,
        'flags' => [],
    ],
    [
        'id' => Entity::pDareBindingDescription,
        'type' => Entity::tAttribute,
        'name' => 'Binding Description (Dare)',
        'descr' => "Describes the binding of a document.",
        'allowedSubjectTypes' => [Entity::tDocument],
        'allowedObjectTypes'=> null,
        'canBeCancelled' => true,
        'singleProperty' => true,
        'flags' => [],
    ],
    [
        'id' => Entity::pDareAcquisition,
        'type' => Entity::tAttribute,
        'name' => 'Acquisition (Dare)',
        'descr' => "Describes the acquisition of a document.",
        'allowedSubjectTypes' => [Entity::tDocument],
        'allowedObjectTypes'=> null,
        'canBeCancelled' => true,
        'singleProperty' => true,
        'flags' => [],
    ],
    [
        'id' => Entity::pDareProvenance,
        'type' => Entity::tAttribute,
        'name' => 'Provenance (Dare)',
        'descr' => "Describes the provenance of a document.",
        'allowedSubjectTypes' => [Entity::tDocument],
        'allowedObjectTypes'=> null,
        'canBeCancelled' => true,
        'singleProperty' => true,
        'flags' => [],
    ],
    [
        'id' => Entity::pDareAdditions,
        'type' => Entity::tAttribute,
        'name' => 'Additions (Dare)',
        'descr' => "Additional information about a document.",
        'allowedSubjectTypes' => [Entity::tDocument],
        'allowedObjectTypes'=> null,
        'canBeCancelled' => true,
        'singleProperty' => true,
        'flags' => [],
    ],
    [
        'id' => Entity::pDareGwNo,
        'type' => Entity::tAttribute,
        'name' => 'Gw No (Dare)',
        'descr' => "Describes the GW number (?) of a document.",
        'allowedSubjectTypes' => [Entity::tDocument],
        'allowedObjectTypes'=> null,
        'canBeCancelled' => true,
        'singleProperty' => true,
        'flags' => [],
    ],
    [
        'id' => Entity::pDareIstc,
        'type' => Entity::tAttribute,
        'name' => 'Istc (Dare)',
        'descr' => "Describes the ISTC number (?) of a document.",
        'allowedSubjectTypes' => [Entity::tDocument],
        'allowedObjectTypes'=> null,
        'canBeCancelled' => true,
        'singleProperty' => true,
        'flags' => [],
    ],
    [
        'id' => Entity::pDareContent,
        'type' => Entity::tAttribute,
        'name' => 'Content (Dare)',
        'descr' => "Describes the content of a document.",
        'allowedSubjectTypes' => [Entity::tDocument],
        'allowedObjectTypes'=> null,
        'canBeCancelled' => true,
        'singleProperty' => true,
        'flags' => [],
    ],
    [
        'id' => Entity::pDareMaterialDescription,
        'type' => Entity::tAttribute,
        'name' => 'Material Description (Dare)',
        'descr' => "Describes the material of a document.",
        'allowedSubjectTypes' => [Entity::tDocument],
        'allowedObjectTypes'=> null,
        'canBeCancelled' => true,
        'singleProperty' => true,
        'flags' => [],
    ],
    [
        'id' => Entity::pDareOrigin,
        'type' => Entity::tAttribute,
        'name' => 'Origin (Dare)',
        'descr' => "Describes the origin of a document.",
        'allowedSubjectTypes' => [Entity::tDocument],
        'allowedObjectTypes'=> null,
        'canBeCancelled' => true,
        'singleProperty' => true,
        'flags' => [],
    ]
];

class DocumentPredicates implements PredicateDefiner
{

    /**
     * @inheritDoc
     */
    public function getEntityDefinitions(): array
    {
       return $this->getPredicateDefinitions();
    }

    /**
     * @inheritDoc
     */
    public function getPredicateDefinitions(): array
    {
       return DefsFromArray::getPredicateDefinitionsFromArray(DocumentPredicateDefs);
    }

    /**
     * @inheritDoc
     */
    public function getStatements(): array
    {
        return [];
    }
}