#
# Configuration for typesetting server
#
#  (paths must be given in terms of the server/container that runs the server)
#

nodeService:
  # Port to listen on (optional, defaults to 4711)
  port: 4711

  # Temporary directory for intermediate files (REQUIRED)
  tmpDir: /var/apm/node-service-tmp

  # Log file (REQUIRED)
  logFile: /var/apm/logs/node-service/server.log

  # Python executable to use (optional, defaults to '/usr/bin/python3')
  pythonExecutable: /usr/bin/python3

  # Path to PDF renderer (optional, defaults to current directory at execution time)
  pdfRendererPath: /opt/apm/node-service

